### ISSUE TITLE
Enable XML mode automatically

### ISSUE THREAD

**Issue by waba4mume** [waba4mume/play-mume#1]
Tell MUME to enable XML mode silently upon (re)connection.

This should be very easy, just a matter of sending the right line (help m p c) in MumeXmlParser.connected(), in mume.mapper.js.

**Comment by nschimme** [comment]
This is already do-able using MUME MPI commands:
https://github.com/MUME/MMapper/blob/5abaf52e7efaa5ee66f246994409f775e83d96bb/src/proxy/proxy.cpp#L225-L229

**Comment by waba4mume** [comment]
Yes, that's what I wrote (help m p c). The task should be "easy", as tagged.
