### ISSUE TITLE
Provide a MM2 basemap in JSON format for performance testing

### ISSUE THREAD

**Issue by waba4mume** [waba4mume/play-mume#3]
We need a JSON version of the MM2 map to fix possible loading and displaying performance issues in the web client map display as early as possible.

Preferably this will be a basemap and not a full map, so that we can just host it somewhere and everyone can try it out.

Eventually we'll need this nicely integrated in MM2, but for now any horrible hack will do. Also, we may have to optimize the format so don't spend too much time on this first attempt.

Expected format : a text file formatted like the hardcodedMapData variable in mume.mapper.js.

**Comment by nschimme** [comment]
I have some serious doubts if we want to follow MMapper's strategy here. Wouldn't it be better to instead use a server side approach and have an official MUME map that we host and stream as needed rather than having each client need to download and then hash to identify the positioning of themselves?

**Comment by waba4mume** [comment]
The current approach has two huge advantages IMHO: it can be done by anyone at any time. Do note that there is only a single, official map, for now clients will not customize it by exploring.

What did you have in mind, though?
1. Who figures out the current location and how? Is it a roomid sent by the server, a webserver-side proxy that does the room matching, does the MUME server send a map portion with a you-are-here flag?
2. How does the webclient get the map data? Is it split in areas and HTTP-downloaded as needed, sent by the MUME server as a Telnet extension?

-Waba.

-------- Original Message --------

**Comment by waba4mume** [comment]
I took care of this in my wip-json2 MMapper branch.
